spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
  jwt:
    secret: tininfadsklfneiwoamekmrkmakldkfvionzbclvknaaaaaaaaiiiirenkirnekrneknkndfmzncxvzmciei
    expiration: 86400

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.security: trace
